### PR TITLE
Update last name: Klicpera to Gasteiger

### PR DESCRIPTION
**Pull request by gasteigerjo**
I have recently changed my name from Johannes Klicpera to Johannes Gasteiger. Since paper authorship is crucial for my future career I would like to update our publication at ICML 2020 accordingly. This PR updates the paper "Efficient Robustness Certificates for Discrete Data: Sparsity-Aware Randomized Smoothing for Graphs, Images and More" to reflect this change.

Thank you for your support! I hope it is also possible to update the metadata accordingly.

### CODE REVIEW

**Comment by mrksr** [comment]
Hi @gasteigerjo, thank you for reaching out and opening this PR! We're happy to make the change.
Could you amend this PR to also change the bib-file in the root of this repo? That should update the website and make sure your name is consistent.

Your request prompted some discussion about whether or not we should change publications of non-recent proceedings, as especially a name change could be tricky. While we can change the proceedings, we cannot change citations of your paper that refer to the old name. So changing your name and therefore your publication could confuse people and systems. Nonetheless, we're convinced that it should be your choice. It would be great to hear how the name change will play out. Does it make no difference, or are downstream projects such as indexers confused and you might run into problems? I guess we'll have to try and see. I'd also love to hear your thoughts of cause :).

**Comment by gasteigerjo** [comment]
I've changed the bib-file in a 2nd commit. The 2 commits should merge nicely into one if you squash-and-merge.

That is indeed a good point, and I've thought about the pros and cons for some time. From my perspective, I want to have a single, consistent, and recognizable author name in the future. Having some publications with the old name and others with the new name would undermine this goal.
There are 2 parts about the confusion: Indexers and readers. I hope that indexers will be able to recognize this or alert me. ICLR already changed my name and Google Scholar seems fine so far. Readers might be confused because they search for the paper with my old name and find the paper with the new name. That will be inconvenient, but from my perspective I prefer it when people encounter this confusion and hopefully realize that my name has changed. Otherwise they would continue to think that my old and new names are actually two different authors. I will leave a comment on arXiv, GitHub and other supplementary websites to help people with this.

**Comment by mrksr** [comment]
Great, thanks for the change! Will merge it now.
Good to know that things worked out nicely with ICLR. You're quite right about some confusion potentially being a good thing :).

**Comment by gasteigerjo** [comment]
Thank you! :)

**Pull request merged**
