### PR TITLE
Fixed error in abstract

### PR DESCRIPTION
**Pull request by gvinciguerra**
Hello. I changed the phrase "space and time occupancy" to "space and time complexity" in the paper abstract and updated icml20.bib and the paper post accordingly.

### CODE REVIEW

**Review by lawrennd — CHANGES_REQUESTED** [review]
Thanks! I can't merge until you can give confirmation that the conference editors are happy with the change to a PDF. Could you provide this? 

It can be a written statement from you confirming who you've got approval from in the issue log. Then I can merge.

**Comment by gvinciguerra** [comment]
Hi Neil,
I'm about to request the permission from the conference editors. I'm sorry I didn't do it before creating the PR; I didn't know the protocol 😊
I'll get back to you as soon as I have an answer. Thank you for your time.

**Comment by lawrennd** [comment]
No problem at all! It's an emerging protocol ;-)

**Comment by gvinciguerra** [comment]
I received a negative answer from the ICML organising committee. In previous years there were floods of requests for changes, so this year they removed this possibility.
I'm closing this pull request. Thanks again @lawrennd :)

**Pull request closed without merging**
