### PR TITLE
Fixed error author names and comments

### PR DESCRIPTION
**Pull request by xxchenxx**
Changed author names from AEIOU to the correct author names, no other correction was made.

### CODE REVIEW

**Comment by xxchenxx** [comment]
I updated the main paper, which contained some wrong author names (random characters). Didn't know how these were generated.

**Review by lawrennd — APPROVED** [review]
Confirming updated names match those in the yaml file and that original PDF was broken.

**Comment by lawrennd** [comment]
Thanks for the fix!

**Comment by xxchenxx** [comment]
Thanks for the fast response!

**Pull request merged**
